jobs:
  include:
  - language: java
    jdk: oraclejdk10

    git:
      depth: false

    cache:
      directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'

    addons:
      sonarcloud:
        organization: chrootlogin-github
        token:
          secure: ytU3nQd7/LmB8K0SrJ6JmnB4k9d6rIy4UUr7Qc6S+dHK9a8thEKp5YbSbijBglH1LFfyFckm9KIeGhLisvqDur2TWo8jEMAmWTjdN/KiDAoZIBmvTpW3hTnkk7g9+kYwb5QL27Qbccl4XUgjhUaoOtTqOijGf3SGf737zdazOQUN8UFC/aiyUVicPLlsBpbROH0bzXc+GA0Ygmkfcd2etyU1+w9gRHLUQlcKiMcIbOHKkHnaHr0uNCoNCG3gCff4fcAHY5BFZr+jF/YN2oTLBRa9o4zyN3/K/5jQUASQo8FRnyeH0EqS+bLrYJqbb4NBeYb//FlRQHTspNyBBRHUaxssDOpJM6oeK/qI8sy/Z9s7sM13OGqCvN9He/2fnhXdHzQoWXLaaXnfsW3Xlhwaqeo6otBVFYrf3GDH650ahA1tHgsE1Q43qZA3/7Qbowx5MaoFhVIE7x2ujhdH+XHQJRUTmG8c37qn2a0cSObtOEUjdSaXeHhoq/FmAWldM/GVaAhXL4Ik+kVqtBfKH9bEiKk4K46r8H6lC3hJyAPKStCdBtIb30JCmpIZ5GCqFaWAd2UqeE8ZAye7Z91nMyqeqTkksj6ZmpSguXS1NlgkkH+rpNOsGZQ39ZVSlD1eyq7/wTSaD4XJc/+JwBdOs2iqexhFCLAO4aqHphFF8z+GkOk=

    install:
    - curl -L "https://dl.bintray.com/rootlogin/go-docstore/master/go-docstore" -o $HOME/go-docstore
    - chmod +x $HOME/go-docstore

    before_script:
    - |
      export SESSION_KEY=not-a-safe-key
      export DB_PATH=/tmp/data.db
      $HOME/go-docstore &
      GO_DOCSTORE_PID=$!

    script:
    - mvn install
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

    after_script:
    - kill -9 $GO_DOCSTORE_PID

notifications:
  email:
  - hello@rootlogin.ch
  pushover:
    api_key:
      secure: V4/O//HtWGTZBJ3Ux66JHFn8lhvFLS8l6YdS4jA5ctZ09EcaHZX9hFoSvmzc7WYZQytvlr+Zzegsh/rYaQ3/UihvH/WBTzonFnsQQmY6uN9PadVK/SdjGPOVgCQoMfdpiHllpFsh/MnyOblClADz2Ancf3zZiSaRGemeZyPL1zcSrtjmejCrx7JMfzw6zeU0h/9liR0Y5+9ZmQHZG63gd70Ol5ul0RzGoIfmRHSdNBPtcNSgYlMop07WOsA3etmS8jtnYF33v7YQF/SWb6oABPyJQwA5+5g+RF6fj9uITMWW/aWk0ove2KBJ58N2TnyOSWpel5w8DYrtZEE5DNTOBTThhJSb88sa+wyZ2dSb+DgWi7jZSNfI50G7Nf+H+eOviLNIx0KzNC95jAuSL/zLGwriqq55mfMIQWs2tdoprLqpelkfwgo03Un9KphYS3OhKl42NKHoLaIG6MyHJCna9RcSEMHNn85E0pmvnqyhHlQZskx9zmPOTruktRXXG3EbWKQjD2p1nml3a5U45+WalrgCg70LXaduALqLQsilaVWfFwR6XB8AGsst//btltZk2iqK8ryLELiZsExYy8wj5fv0QD2U64/ht5X85d9QH2UqlT0FB9QdNfqWpbyVnsC1Kw9t3yxuwXvRHU1bvkK7FpnTMcAuGYT4JE7UFdXSdT8=
    users:
    - secure: 24eBUpIQ5pLTiSQetDmeJM34d3vgX74joTvLIbN6G7RA7BMARDf3bwOYb6xiMHXeX8frDDX65fmzGQct6vROlPIHvpalxT03+F9bAUgyvWdHcSHp3pSlFO0EdhVkeo5cMC/ICeSaqkdF1RN5VoW5UrXy7/BKD0dbK36NKfOONwopxjGmZGKBqrkO5Qq1Tfr87oXOVPebSkeCjjRlQFTe9w951Bj9rIGl1KzlTsrH3EbQhrVrDd2EXn5+KjYBY8eW11DP+zQpHQWMtRPpSFPyJV7uRNtK7z387tDSHFXcTM7O5Q5FHsmA9hQbR9/+zF3Y5kCCc/82612GRa9taUc21Xx6FkZUTmDYHJe0u2adyKlTW9DJ+mQt5c4mHdGiGQyeuOUR2nNF/OPwkmtjMSQJflneL3QIjjXNX8zSXakwdKHBnpvTPI6MNonKj586hPdiAaTairgVXQ6zwxWbtvCU48Ew/3C7VHop1KpEl3heIQguRD3YBpL4nMny8T+ywTZhtN5LC5zTtNh0pQ6bmOekRr/I8Xz8d2QkwJdTAoVtj9dnnqAk70TVp0uhJNAAWyivfuabFGXtzCFd1TSsv0xxSy0oGKnFFvNBt84kXHLzVb91mdauafX764YXGeJS9SuK8RpVHkseY8u4pW3/iK3k13S1uediZcZso7qa3DVBXJs=
    on_success: always
    on_failure: always